server:
  port: 8040
spring:
  h2:
    console:
      path: /h2
      enabled: true
  datasource:
    url: jdbc:h2:mem:midb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create